### ISSUE TITLE
/playtime offline hráčů neukazuje pozici v TOPu.

### ISSUE THREAD

**Issue by tabels** [ignissak/SurvCore#10]
/playtime offline hráčů neukazuje pozici v TOPu.

nabbed from CuteDejw lol

**Comment by tabels** [comment]
also dis error
`
> [23:09:12 WARN]: java.lang.NullPointerException
> [23:09:12 WARN]: at sk.ignissak.su.survcore.SQLManager.getTopPlaytime(SQLManager.java:532)
> [23:09:12 WARN]: at sk.ignissak.su.survcore.commands.Playtime.onCommand(Playtime.java:39)
> [23:09:12 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [23:09:12 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
> [23:09:12 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
> [23:09:12 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:684)
> [23:09:12 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:459)
> [23:09:12 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:418)
> [23:09:12 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
> [23:09:12 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
> [23:09:12 WARN]: at java.lang.Thread.run(Thread.java:748)`

**Comment by ignissak** [comment]
Fixed.
